<?xml version="1.0" encoding="UTF-8"?>


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="Privilege">
		<xs:sequence minOccurs="0">

				<xs:element name="URI" type="xs:anyURI" minOccurs="0" />			
				<xs:element name="ObjectId" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation> The primary key for this table. A globally unique, system-generated identifier for a Privilege object.</xs:documentation>
					</xs:annotation>
				</xs:element>
				
				<xs:element name="DisplayName" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>The localized name of the privilege, which is displayed in the SA. The localized version of the string.</xs:documentation>
					</xs:annotation>
				</xs:element>
				
			<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax" />
			<xs:element name="NullFields"> 
				<xs:simpleType>  
					<xs:list itemType="xs:string"/> 
				</xs:simpleType> 
			</xs:element>
		</xs:sequence>
	</xs:complexType>	
	<xs:element name="Privilege" type="Privilege"/>
	<xs:element name="Privileges">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Privilege" type="Privilege" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="total" type="xs:integer"/>
		</xs:complexType>
	</xs:element>	
</xs:schema>
