#!/usr/bin/env python3

"""
Clean up empty mailboxes from Cisco Unity Connection.

Read mailbox usage data from a CSV file generated by check_userMailboxUsage.py.
Delete mailboxes with 0 size and export mailboxes with >0 size to a new CSV.

Usage:
    python3 cleanup_emptyMailboxes.py

The script is interactive and will prompt for:
    CUC JSON File (cuc-info.json): path to the JSON file with server/login
        info (default: cuc-info.json). If the password field in that file
        is blank, you will be prompted to enter it.
    Prompt for deletes?: (y/n): choose 'y' to be prompted before deleting each
        empty mailbox, or 'n' (default) to delete all empty mailboxes automatically.
    Input CSV file name (default: mailboxes.csv): path to the CSV file with extensions
    Output file name (default: mailbox_usage_remaining.csv): path to output CSV file
        with mailboxes that have >0 size

CSV Input Format (1 column, any header name):
extension
2001
2002

CSV Output Format (remaining mailboxes):
dtmfAccessID,alias,mailboxSize
2002,user2,123.45

"""

from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from csv import reader, writer
import json
import time
import requests
import urllib3
from requests.auth import HTTPBasicAuth
import logging
from logging.handlers import StreamHandler
import getpass
from lxml import etree
from setup.logger import setup_logger

log_filename_prefix = 'cleanup-emptyMailboxes-'


def load_server_config(config_file):
    """Load CUC server configuration from JSON file.

    Args:
        config_file (Path): Path to JSON config file

    Returns:
        dict: Configuration with keys: server, username, password, version
    """
    with open(config_file) as json_data_file:
        config = json.load(json_data_file)

    return config


def get_user_mailbox_usage(http_session, cuc_server, extension):
    """
    Query a user by extension and retrieve mailbox size.

    Args:
        http_session: Requests session with auth configured
        cuc_server (string): CUC server address
        extension (string): Extension number to look up

    Returns:
        dict: Result with keys 'success', 'dtmfAccessId', 'alias', 'mailboxSize', 'uri', 'error'
    """
    try:
        base_url = f'https://{cuc_server}/vmrest'

        logger.debug(f'Querying mailbox usage for extension: {extension}')

        users_url = f'{base_url}/users/'
        users_response = http_session.get(users_url, verify=False)
        users_response.raise_for_status()

        root = etree.fromstring(users_response.content)
        user_elements = root.findall('.//User')

        matched_user = None
        for user_elem in user_elements:
            user_dict = {}
            for child in user_elem:
                user_dict[child.tag] = child.text

            if user_dict.get('DtmfAccessId') == extension:
                matched_user = user_dict
                break

        if not matched_user:
            logger.warning(f'No user found with extension: {extension}')
            return {'success': False, 'dtmfAccessId': extension, 'alias': '', 'mailboxSize': '', 'uri': '', 'error': f'No user found'}

        user_alias = matched_user.get('Alias', 'N/A')
        user_dtmf = matched_user.get('DtmfAccessId', extension)
        user_uri = matched_user.get('URI', '')

        if not user_uri:
            logger.error(f'No URI found for extension {extension}')
            return {'success': False, 'dtmfAccessId': user_dtmf, 'alias': user_alias, 'mailboxSize': '', 'uri': '', 'error': 'No URI found'}

        mailbox_url = f'https://{cuc_server}{user_uri}/mailboxattributes'
        mailbox_response = http_session.get(mailbox_url, verify=False)
        mailbox_response.raise_for_status()

        mailbox_root = etree.fromstring(mailbox_response.content)

        mailbox = {}
        if mailbox_root.tag == 'MailboxAttributes':
            for child in mailbox_root:
                mailbox[child.tag] = child.text
        else:
            mailbox_elem = mailbox_root.find('.//MailboxAttributes')
            if mailbox_elem is not None:
                for child in mailbox_elem:
                    mailbox[child.tag] = child.text

        current_size_bytes = int(mailbox.get('ByteSize', 0))
        current_size_mb = round(current_size_bytes / (1024 * 1024), 2)

        logger.info(f'Retrieved mailbox usage for {user_alias} ({user_dtmf}): {current_size_mb} MB')
        return {'success': True, 'dtmfAccessId': user_dtmf, 'alias': user_alias, 'mailboxSize': current_size_mb, 'uri': user_uri, 'error': ''}

    except requests.exceptions.RequestException as e:
        error_msg = f'API request failed: {str(e)}'
        logger.error(error_msg)
        return {'success': False, 'dtmfAccessId': extension, 'alias': '', 'mailboxSize': '', 'uri': '', 'error': error_msg}
    except (KeyError, ValueError) as e:
        error_msg = f'Error parsing response: {str(e)}'
        logger.error(error_msg)
        return {'success': False, 'dtmfAccessId': extension, 'alias': '', 'mailboxSize': '', 'uri': '', 'error': error_msg}


def delete_mailbox(http_session, cuc_server, dtmf_access_id, user_uri):
    """
    Delete a user (and their mailbox) via CUC REST API.

    Args:
        http_session: Requests session with auth configured
        cuc_server (string): CUC server address
        dtmf_access_id (string): DTMF access ID (for logging)
        user_uri (string): User URI from CUC API (format: /vmrest/users/{objectid})

    Returns:
        dict: Result with keys 'success', 'error'
    """
    try:
        delete_url = f'https://{cuc_server}{user_uri}'

        logger.info(f'Deleting mailbox for {dtmf_access_id}')

        delete_response = http_session.delete(delete_url, verify=False)
        delete_response.raise_for_status()

        logger.info(f'Successfully deleted mailbox for {dtmf_access_id}')
        return {'success': True, 'error': ''}

    except requests.exceptions.RequestException as e:
        error_msg = f'Failed to delete mailbox for {dtmf_access_id}: {str(e)}'
        logger.error(error_msg)
        return {'success': False, 'error': error_msg}
    except Exception as e:
        error_msg = f'Error deleting mailbox for {dtmf_access_id}: {str(e)}'
        logger.error(error_msg)
        return {'success': False, 'error': error_msg}


def process_mailboxes(http_session, cuc_server, input_file, output_file, prompt_for_deletes):
    """
    Process mailbox CSV: look up mailbox sizes, delete empty ones, export remaining to new CSV.

    Args:
        http_session: Requests session with auth configured
        cuc_server (string): CUC server address
        input_file (string): Path to input CSV with extensions (1 column, any header)
        output_file (string): Path to output CSV with remaining mailboxes
        prompt_for_deletes (bool): Whether to prompt before deleting each mailbox
    """
    try:
        with open(input_file, 'r', encoding='utf8') as my_file:
            csv_file = reader(my_file)
            next(my_file)  # Skip header

            output_rows = []
            deleted_count = 0
            error_count = 0
            checked_count = 0

            for row in csv_file:
                if len(row) > 0:
                    extension = row[0].strip()

                    if extension:
                        checked_count += 1
                        logger.debug(f'Looking up mailbox for extension: {extension}')

                        # Look up the user and their mailbox size
                        mailbox_info = get_user_mailbox_usage(http_session, cuc_server, extension)

                        if not mailbox_info['success']:
                            logger.warning(f'Could not retrieve mailbox info for {extension}: {mailbox_info["error"]}')
                            error_count += 1
                            continue

                        dtmf_access_id = mailbox_info['dtmfAccessId']
                        alias = mailbox_info['alias']
                        mailbox_size = mailbox_info['mailboxSize']
                        user_uri = mailbox_info['uri']

                        logger.debug(f'Checking mailbox: {dtmf_access_id} ({alias}) - Size: {mailbox_size} MB')

                        if mailbox_size == 0:
                            logger.info(f'Empty mailbox found: {dtmf_access_id} ({alias}) - 0 MB')
                            # Empty mailbox - attempt to delete it
                            should_delete = True
                            if prompt_for_deletes:
                                response = input(f'Delete empty mailbox for {dtmf_access_id} ({alias})? (y/n): ')
                                should_delete = response.lower() in ('y', 'yes')

                            if should_delete:
                                delete_result = delete_mailbox(http_session, cuc_server, dtmf_access_id, user_uri)
                                if delete_result['success']:
                                    logger.info(f'Deleted: {dtmf_access_id} ({alias})')
                                    deleted_count += 1
                                else:
                                    logger.warning(f'Could not delete {dtmf_access_id}: {delete_result["error"]} - may not be supported by this CUC version')
                            else:
                                logger.info(f'Skipped deletion of {dtmf_access_id} ({alias})')
                        else:
                            logger.info(f'Retaining mailbox: {dtmf_access_id} ({alias}) - {mailbox_size} MB')
                            # Non-empty mailbox - keep it in output
                            output_rows.append([dtmf_access_id, alias, mailbox_size])

        with open(output_file, 'w', encoding='utf8', newline='') as out_file:
            csv_writer = writer(out_file)
            csv_writer.writerow(['dtmfAccessID', 'alias', 'mailboxSize'])
            csv_writer.writerows(output_rows)

        logger.info(f'Processed {checked_count} extensions')
        logger.info(f'Deleted {deleted_count} empty mailboxes')
        logger.info(f'Encountered {error_count} errors during processing')
        logger.info(f'Exported {len(output_rows)} mailboxes with data to {output_file}')
        print(f'\nResults:')
        print(f'  Checked: {checked_count} extensions')
        print(f'  Deleted: {deleted_count} empty mailboxes')
        print(f'  Errors: {error_count}')
        print(f'  Exported: {len(output_rows)} mailboxes to {output_file}')

    except FileNotFoundError:
        logger.error(f'CSV file not found: {input_file}')
        print(f'Error: CSV file not found: {input_file}')
    except IOError as e:
        logger.error(f'Error reading/writing file: {str(e)}')
        print(f'Error: {str(e)}')


def main():
    """Main menu and workflow."""
    while True:
        prompt_input = input('Prompt for deletes?: (y/n) ') or 'n'
        prompt_for_deletes = prompt_input.lower() in ('y', 'yes')
        break

    input_file = input('Input CSV file name (default: mailboxes.csv): ') or 'mailboxes.csv'
    output_file = input('Output file name (default: mailbox_usage_remaining.csv): ') or 'mailbox_usage_remaining.csv'

    process_mailboxes(http_session, cuc_server, input_file, output_file, prompt_for_deletes)


if __name__ == '__main__':
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    basepath = Path.cwd()

    config_file = input('CUC JSON File (cuc-info.json): ') or 'cuc-info.json'
    if not config_file.endswith('.json'):
        config_file = config_file + '.json'
    config = load_server_config(basepath / config_file)

    cuc_server = config.get('server')
    username = config.get('username')
    password = config.get('password')
    version = config.get('version', '15.0')

    log_path = basepath / 'logs' / (log_filename_prefix + cuc_server + '-' + time.strftime("%Y_%m_%d-%H_%M_%S") + '.log')
    try:
        logger = setup_logger(log_path)
    except (OSError, PermissionError) as e:
        print(f'Warning: Could not write logs to {log_path.parent}')
        print(f'Using stdout-only logging: {e}\n')
        logger = logging.getLogger('cuc_logger')
        logger.setLevel(logging.DEBUG)
        stdout_handler = logging.StreamHandler(sys.stdout)
        message_format = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s", "%Y-%m-%d %H:%M:%S")
        stdout_handler.setFormatter(message_format)
        logger.addHandler(stdout_handler)

    if password == '' or password is None:
        password = getpass.getpass(f'Enter CUC Password for {username}: ')

    logger.info(f'Starting cleanup_emptyMailboxes for server: {cuc_server} (version: {version})')

    http_session = requests.Session()
    http_session.auth = HTTPBasicAuth(username, password)
    http_session.headers.update({'Content-Type': 'application/json'})

    main()

    logger.info('Script completed')
