#!/usr/bin/env python3

"""
Delete Cisco Unity Connection Call Handlers from CSV.

Read call handlers from a CSV file (generated by list_CallHandlers.py) and delete them.

Usage:
    python3 delete_CallHandlers.py

The script is interactive and will prompt for:
    CUC JSON File (cuc-info.json): path to the JSON file with server/login
        info (default: cuc-info.json). If the password field in that file
        is blank, you will be prompted to enter it.
    Prompt for deletes?: (y/n): choose 'y' to be prompted before deleting each
        handler, or 'n' (default) to delete all handlers without prompting.
    Input CSV file name (default: callhandlers.csv): path to the CSV file with
        displayName, extension, and objectId columns

CSV Input Format:
displayName,extension,objectId
Test,,9cb5b41c-7ac4-4a42-a18f-b985d7c3acc0
test2-level2,,f349f979-308b-4fad-b110-f58c132c2cae

"""

from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from csv import DictReader
import json
import time
import requests
import urllib3
from requests.auth import HTTPBasicAuth
import logging
from logging.handlers import StreamHandler
import getpass
from setup.on_prem.logger import setup_logger

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

log_filename_prefix = 'delete-CallHandlers-'


def load_server_config(config_file):
    """Load CUC server configuration from JSON file.

    Args:
        config_file (Path): Path to JSON config file

    Returns:
        dict: Configuration with keys: server, username, password, version
    """
    with open(config_file) as json_data_file:
        config = json.load(json_data_file)

    return config


def prompt_for_password(prompt_text='Password: '):
    """Prompt user for password without echoing to screen."""
    return getpass.getpass(prompt_text)


def read_handlers_from_csv(csv_file):
    """
    Read Call Handlers from CSV file.

    Args:
        csv_file (str): Path to CSV file

    Returns:
        list: List of handler dicts with displayName, extension, and objectId
    """
    handlers = []
    try:
        with open(csv_file, 'r') as f:
            reader = DictReader(f)
            for row in reader:
                if row.get('objectId'):
                    handlers.append({
                        'displayName': row.get('displayName', ''),
                        'extension': row.get('extension', ''),
                        'objectId': row.get('objectId', '')
                    })
        return handlers
    except FileNotFoundError:
        logger.error(f'CSV file not found: {csv_file}')
        raise
    except Exception as e:
        logger.error(f'Error reading CSV file: {e}')
        raise


def delete_call_handler(http_session, cuc_server, handler_name, object_id):
    """
    Delete a single Call Handler.

    Args:
        http_session: Requests session with auth configured
        cuc_server (string): CUC server address
        handler_name (string): Display name of handler (for logging)
        object_id (string): ObjectId of the handler to delete

    Returns:
        dict: Result with keys 'success', 'response', 'error'
    """
    try:
        base_url = f'https://{cuc_server}/vmrest'
        delete_url = f'{base_url}/handlers/callhandlers/{object_id}'

        logger.info(f'Deleting Call Handler: {handler_name} (ID: {object_id})')

        response = http_session.delete(delete_url, verify=False)

        if response.status_code in [200, 204]:
            logger.info(f'Successfully deleted: {handler_name}')
            return {'success': True, 'response': f'Deleted {handler_name}', 'error': ''}
        else:
            logger.error(f'Failed to delete {handler_name}: {response.status_code} - {response.text}')
            return {'success': False, 'response': '', 'error': f'HTTP {response.status_code}: {response.text}'}

    except requests.exceptions.RequestException as e:
        logger.error(f'Error deleting Call Handler {handler_name}: {e}')
        return {'success': False, 'response': '', 'error': str(e)}


def main():
    config_file = input('CUC JSON File (cuc-info.json): ').strip() or 'cuc-info.json'

    if not Path(config_file).exists():
        print(f'Error: Config file {config_file} not found')
        sys.exit(1)

    config = load_server_config(config_file)
    cuc_server = config.get('server')
    username = config.get('username')
    password = config.get('password', '')

    if not password:
        password = prompt_for_password('CUC Password: ')

    global logger
    basepath = Path(__file__).parent
    log_path = basepath / 'logs' / (log_filename_prefix + cuc_server + '-' + time.strftime("%Y_%m_%d-%H_%M_%S") + '.log')
    try:
        logger = setup_logger(log_path)
    except (OSError, PermissionError) as e:
        print(f'Warning: Could not write logs to {log_path.parent}')
        print(f'Using stdout-only logging: {e}\n')
        logger = logging.getLogger('cuc_logger')
        logger.setLevel(logging.DEBUG)
        stdout_handler = logging.StreamHandler(sys.stdout)
        message_format = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s", "%Y-%m-%d %H:%M:%S")
        stdout_handler.setFormatter(message_format)
        logger.addHandler(stdout_handler)

    prompt_deletes = input('Prompt for deletes?: (y/n) ').strip().lower() == 'y'
    csv_file = input('Input CSV file name (callhandlers.csv): ').strip() or 'callhandlers.csv'

    if not Path(csv_file).exists():
        print(f'Error: CSV file {csv_file} not found')
        logger.error(f'CSV file not found: {csv_file}')
        sys.exit(1)

    try:
        handlers = read_handlers_from_csv(csv_file)

        if not handlers:
            print('No handlers found in CSV file')
            logger.warning('No handlers found in CSV file')
            sys.exit(0)

        logger.info(f'Read {len(handlers)} handlers from {csv_file}')
        print(f'\nFound {len(handlers)} Call Handlers to delete\n')

        http_session = requests.Session()
        http_session.auth = HTTPBasicAuth(username, password)
        http_session.headers.update({'Content-Type': 'application/xml'})

        deleted_count = 0
        failed_count = 0

        for handler in handlers:
            display_name = handler.get('displayName', '')
            object_id = handler.get('objectId', '')

            if prompt_deletes:
                confirm = input(f'Delete "{display_name}"? (y/n): ').strip().lower()
                if confirm != 'y':
                    logger.info(f'Skipped: {display_name}')
                    print(f'Skipped: {display_name}')
                    continue

            result = delete_call_handler(http_session, cuc_server, display_name, object_id)

            if result['success']:
                deleted_count += 1
                print(f'Deleted: {display_name}')
            else:
                failed_count += 1
                print(f'Failed: {display_name} - {result["error"]}')

        logger.info(f'Delete operation completed. Deleted: {deleted_count}, Failed: {failed_count}')
        print(f'\nDelete completed. Total deleted: {deleted_count}, Failed: {failed_count}')

    except Exception as e:
        logger.error(f'Script failed: {e}')
        sys.exit(1)


if __name__ == '__main__':
    main()
