#!/usr/bin/env python3
# TITLE: Delete Call Handlers

"""
Delete Cisco Unity Connection Call Handlers from a CSV file.

Read call handlers from a CSV file (generated by list_CallHandlers.py) and
delete them by ObjectId.

WARNING: ObjectIds are per-cluster. In multi-cluster mode the same CSV file
is applied to every selected cluster; only use multi-cluster mode when the
CSV's objectIds actually belong to each of those clusters. Otherwise run
the script once per cluster, using a CSV exported from that same cluster.

Usage:
    python3 delete_CallHandlers.py

The script is interactive and will prompt for:
    CUC Cluster: select from clusters.csv or provide manually
    Credentials: checks stored credentials in credentials.env
    Use multiple clusters?: (y/n): choose 'y' to apply the same CSV to every
        CUC cluster in clusters.csv, or 'n' (default) to pick a single cluster.
    Prompt for deletes?: (y/n): choose 'y' to be prompted before deleting each
        handler, or 'n' (default) to delete all handlers without prompting.
    Input CSV file [_DATA/callhandlers.csv]: path to the CSV file with
        displayName, extension, and objectId columns

CSV Input Format (displayName, extension, objectId):
Test,,9cb5b41c-7ac4-4a42-a18f-b985d7c3acc0
test2-level2,,f349f979-308b-4fad-b110-f58c132c2cae

Output: none (deletes call handlers in place)
Logs: ../_logs/<timestamp>-delete-call-handlers.log
"""

from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from csv import DictReader
from datetime import datetime
import urllib3
from setup.logger import setup_logger
from setup.prompt_utils import prompt_yes_no
from setup.multi_object_loader import (
    get_object_for_single_operation,
    load_credentials,
    get_objects_for_multi_operation,
    load_credentials_for_multi_objects
)
from cucAPI import CUC


def read_handlers_from_csv(csv_file, logger):
    """
    Read Call Handlers from CSV file.

    Args:
        csv_file (str): Path to CSV file
        logger: logger instance

    Returns:
        list: List of handler dicts with displayName, extension, and objectId
    """
    handlers = []
    with open(csv_file, 'r', encoding='utf8') as f:
        reader = DictReader(f)
        for row in reader:
            if row.get('objectId'):
                handlers.append({
                    'displayName': row.get('displayName', ''),
                    'extension': row.get('extension', ''),
                    'objectId': row.get('objectId', '')
                })
    logger.info('Read %d handlers from %s', len(handlers), csv_file)
    return handlers


def delete_handlers(cuc, handlers, logger, prompt_deletes=False):
    """
    Delete a list of Call Handlers from CUC.

    Args:
        cuc: CUC API client instance
        handlers (list): List of handler dicts with displayName and objectId
        logger: logger instance
        prompt_deletes (bool): If True, confirm before deleting each handler

    Returns:
        tuple: (deleted_count, failed_count, skipped_count)
    """
    deleted_count = 0
    failed_count = 0
    skipped_count = 0

    for handler in handlers:
        display_name = handler.get('displayName', '')
        object_id = handler.get('objectId', '')

        if prompt_deletes:
            confirm_delete = prompt_yes_no(f'Delete "{display_name}"?', default=False)
            if not confirm_delete:
                logger.info('Skipped: %s', display_name)
                print(f'Skipped: {display_name}')
                skipped_count += 1
                continue

        logger.info('Deleting Call Handler: %s (ID: %s)', display_name, object_id)
        result = cuc.delete_call_handler(object_id)
        if result.get('success'):
            logger.info('Successfully deleted: %s', display_name)
            print(f'Deleted: {display_name}')
            deleted_count += 1
        else:
            logger.error('Failed to delete %s: %s', display_name, result.get('error'))
            print(f'Failed: {display_name} - {result.get("error")}')
            failed_count += 1

    return deleted_count, failed_count, skipped_count


def run_operation_on_cluster(basepath, cluster_data, handlers, prompt_deletes, cluster_credentials, logger):
    """
    Delete the given Call Handlers on a single cluster.

    Args:
        basepath (Path): repo cuc/ directory
        cluster_data (dict): cluster dict from clusters.csv (name, server, version)
        handlers (list): handler dicts to delete (shared across clusters)
        prompt_deletes (bool): confirm before deleting each handler
        cluster_credentials (dict): cluster_name -> (username, password)
        logger: logger instance

    Returns:
        bool: True if no deletes failed, False otherwise
    """
    cluster_name = cluster_data.get('name', 'unknown')
    server = cluster_data.get('server', 'unknown')
    try:
        username, password = cluster_credentials[cluster_name]
        version = cluster_data.get('version')

        cuc = CUC(username=username, password=password, server=server, version=version)

        logger.info('=' * 60)
        logger.info('Processing cluster: %s (%s)', cluster_name, server)
        logger.info('=' * 60)

        deleted, failed, skipped = delete_handlers(cuc, handlers, logger, prompt_deletes=prompt_deletes)

        logger.info('Completed cluster: %s. Deleted: %d, Failed: %d, Skipped: %d',
                     cluster_name, deleted, failed, skipped)
        print(f"✓ Completed {cluster_name} ({server}) - Deleted: {deleted}, Failed: {failed}, Skipped: {skipped}")
        return failed == 0
    except Exception as e:
        logger.error('Exception on cluster %s: %s', cluster_name, str(e))
        print(f"✗ Failed on {cluster_name}: {str(e)}")
        return False


def run_on_all_clusters(basepath, clusters_data, handlers, prompt_deletes, logger):
    """Apply the same delete list to every selected cluster sequentially."""
    print(f"\nProcessing {len(clusters_data)} clusters...\n")

    print("=" * 80)
    print("Loading Credentials")
    print("=" * 80)
    use_same = prompt_yes_no('Use same credentials for all clusters?', default=True)
    cluster_credentials = load_credentials_for_multi_objects('CUC', clusters_data, use_same=use_same)

    successful = 0
    failed = 0
    for cluster in clusters_data:
        if run_operation_on_cluster(basepath, cluster, handlers, prompt_deletes, cluster_credentials, logger):
            successful += 1
        else:
            failed += 1

    print(f"\n{'=' * 60}")
    print(f"Completed: {successful} successful, {failed} failed")
    print(f"{'=' * 60}")


if __name__ == '__main__':
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    log_file = f"../_logs/{timestamp}-delete-call-handlers.log"
    logger = setup_logger(log_file)
    logger.info("Delete Call Handlers - Started")

    basepath = Path.cwd()

    clusters_data = get_objects_for_multi_operation(basepath, 'CUC', server_type='publisher')
    use_multiple = False
    if clusters_data:
        use_multiple = prompt_yes_no(f'{len(clusters_data)} clusters found. Use multiple clusters?', default=False)
        if use_multiple:
            print('\nWARNING: ObjectIds are per-cluster. The same CSV will be applied to every')
            print('selected cluster; make sure the CSV objectIds actually belong to each cluster.')
            logger.warning('Multi-cluster delete requested; the same CSV objectIds will be applied to every selected cluster')

    prompt_deletes = prompt_yes_no('Prompt for deletes?', default=False)
    default_csv = str(basepath.parent / '_DATA' / 'callhandlers.csv')
    csv_file = input(f'Input CSV file [{default_csv}]: ').strip() or default_csv

    if not Path(csv_file).exists():
        print(f'Error: CSV file {csv_file} not found')
        logger.error('CSV file not found: %s', csv_file)
        sys.exit(1)

    handlers = read_handlers_from_csv(csv_file, logger)
    if not handlers:
        print('No handlers found in CSV file')
        logger.warning('No handlers found in CSV file')
        sys.exit(0)

    print(f'\nFound {len(handlers)} Call Handlers to delete\n')

    if clusters_data and use_multiple:
        run_on_all_clusters(basepath, clusters_data, handlers, prompt_deletes, logger)
    else:
        cluster = get_object_for_single_operation(basepath, 'CUC', server_type='publisher')
        if not cluster:
            print("Error: Unable to load cluster information")
            sys.exit(1)
        username, password = load_credentials('CUC', cluster['name'])
        cluster_credentials = {cluster['name']: (username, password)}
        run_operation_on_cluster(basepath, cluster, handlers, prompt_deletes, cluster_credentials, logger)

    logger.info("Delete Call Handlers - Completed")
