#!/usr/bin/env python3

"""
Delete Cisco Unity Connection Call Handlers from CSV.

Read call handlers from a CSV file (generated by list_CallHandlers.py) and delete them.

Usage:
    python3 delete_CallHandlers.py

The script is interactive and will prompt for:
    CUC Cluster: select from clusters.csv or provide manually
    Credentials: checks stored credentials in credentials.env
    Prompt for deletes?: (y/n): choose 'y' to be prompted before deleting each
        handler, or 'n' (default) to delete all handlers without prompting.
    Input CSV file name (default: callhandlers.csv): path to the CSV file with
        displayName, extension, and objectId columns

CSV Input Format:
displayName,extension,objectId
Test,,9cb5b41c-7ac4-4a42-a18f-b985d7c3acc0
test2-level2,,f349f979-308b-4fad-b110-f58c132c2cae

"""

from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from csv import DictReader
import time
import requests
import urllib3
from requests.auth import HTTPBasicAuth
from datetime import datetime
from setup.logger import setup_logger
from setup.multi_object_loader import get_object_for_single_operation, load_credentials

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

log_filename_prefix = 'delete-CallHandlers-'


def read_handlers_from_csv(csv_file):
    """
    Read Call Handlers from CSV file.

    Args:
        csv_file (str): Path to CSV file

    Returns:
        list: List of handler dicts with displayName, extension, and objectId
    """
    handlers = []
    try:
        with open(csv_file, 'r') as f:
            reader = DictReader(f)
            for row in reader:
                if row.get('objectId'):
                    handlers.append({
                        'displayName': row.get('displayName', ''),
                        'extension': row.get('extension', ''),
                        'objectId': row.get('objectId', '')
                    })
        return handlers
    except FileNotFoundError:
        logger.error(f'CSV file not found: {csv_file}')
        raise
    except Exception as e:
        logger.error(f'Error reading CSV file: {e}')
        raise


def delete_call_handler(http_session, cuc_server, handler_name, object_id):
    """
    Delete a single Call Handler.

    Args:
        http_session: Requests session with auth configured
        cuc_server (string): CUC server address
        handler_name (string): Display name of handler (for logging)
        object_id (string): ObjectId of the handler to delete

    Returns:
        dict: Result with keys 'success', 'response', 'error'
    """
    try:
        base_url = f'https://{cuc_server}/vmrest'
        delete_url = f'{base_url}/handlers/callhandlers/{object_id}'

        logger.info(f'Deleting Call Handler: {handler_name} (ID: {object_id})')

        response = http_session.delete(delete_url, verify=False)

        if response.status_code in [200, 204]:
            logger.info(f'Successfully deleted: {handler_name}')
            return {'success': True, 'response': f'Deleted {handler_name}', 'error': ''}
        else:
            logger.error(f'Failed to delete {handler_name}: {response.status_code} - {response.text}')
            return {'success': False, 'response': '', 'error': f'HTTP {response.status_code}: {response.text}'}

    except requests.exceptions.RequestException as e:
        logger.error(f'Error deleting Call Handler {handler_name}: {e}')
        return {'success': False, 'response': '', 'error': str(e)}


def main(http_session, cuc_server, logger):
    """Main menu and operation logic."""
    prompt_deletes = input('Prompt for deletes?: (y/n) ').strip().lower() == 'y'
    csv_file = input('Input CSV file name (callhandlers.csv): ').strip() or 'callhandlers.csv'

    if not Path(csv_file).exists():
        print(f'Error: CSV file {csv_file} not found')
        logger.error(f'CSV file not found: {csv_file}')
        sys.exit(1)

    try:
        handlers = read_handlers_from_csv(csv_file)

        if not handlers:
            print('No handlers found in CSV file')
            logger.warning('No handlers found in CSV file')
            sys.exit(0)

        logger.info(f'Read {len(handlers)} handlers from {csv_file}')
        print(f'\nFound {len(handlers)} Call Handlers to delete\n')

        deleted_count = 0
        failed_count = 0

        for handler in handlers:
            display_name = handler.get('displayName', '')
            object_id = handler.get('objectId', '')

            if prompt_deletes:
                confirm = input(f'Delete "{display_name}"? (y/n): ').strip().lower()
                if confirm != 'y':
                    logger.info(f'Skipped: {display_name}')
                    print(f'Skipped: {display_name}')
                    continue

            result = delete_call_handler(http_session, cuc_server, display_name, object_id)

            if result['success']:
                deleted_count += 1
                print(f'Deleted: {display_name}')
            else:
                failed_count += 1
                print(f'Failed: {display_name} - {result["error"]}')

        logger.info(f'Delete operation completed. Deleted: {deleted_count}, Failed: {failed_count}')
        print(f'\nDelete completed. Total deleted: {deleted_count}, Failed: {failed_count}')

    except Exception as e:
        logger.error(f'Script failed: {e}')
        sys.exit(1)


if __name__ == '__main__':
    basepath = Path.cwd()

    # Load cluster information from clusters.csv or interactive input
    cluster = get_object_for_single_operation(basepath, 'CUC', server_type='publisher')
    if not cluster:
        print("Error: Unable to load cluster information")
        sys.exit(1)

    # Load credentials
    username, password = load_credentials('CUC', cluster['name'])

    cuc_server = cluster['server']

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    log_file = f"../_logs/{timestamp}-delete-callhandlers-{cuc_server}.log"
    logger = setup_logger(log_file)
    logger.info("Delete Call Handlers - Started")

    http_session = requests.Session()
    http_session.auth = HTTPBasicAuth(username, password)
    http_session.headers.update({'Content-Type': 'application/xml'})

    main(http_session, cuc_server, logger)

    logger.info('Script completed')
